import discord
from discord import app_commands
from discord.ext import commands, tasks
from datetime import datetime, timezone, timedelta
from typing import Optional
import re
import motor.motor_asyncio # อย่าลืม pip install motor

class Ban(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.embed_color = 0x2B2D31
        
        # 📊 MONGODB CONNECTION (ปรับแก้ URL และชื่อ Database ตามของคุณได้เลย)
        self.mongo_client = motor.motor_asyncio.AsyncIOMotorClient("mongodb+srv://FeroX:Devs@feroxmongo02.ata40kl.mongodb.net/?appName=FeroXMongo02")
        self.db = self.mongo_client["discord_bot_mainframe"]
        self.ban_collection = self.db["temp_bans"]
        
        # เริ่มต้นระบบตรวจสอบเวลา Unban แบบอัตโนมัติ
        self.unban_monitor_loop.start()

    def cog_unload(self):
        self.unban_monitor_loop.cancel()

    async def cog_load(self):
        # ⚡ สร้าง TTL Index ให้ MongoDB ลบข้อมูลตัวเองอัตโนมัติเมื่อถึงเวลา 'unban_time'
        # วิธีนี้ปลอดภัย ข้อมูลไม่ล้นโควต้าแน่นอน
        await self.ban_collection.create_index("unban_time", expireAfterSeconds=0)

    # ⏱️ TIME PARSER UTILITY
    def parse_ duration(self, duration_str: str) -> Optional[timedelta]:
        """แปลงข้อความ 1m, 1h, 1d, 1w ให้เป็นวัตถุ timedelta"""
        match = re.match(r"^(\d+)([mhdw])$", duration_str.lower())
        if not match:
            return None
        
        amount = int(match.group(1))
        unit = match.group(2)
        
        if unit == 'm': return timedelta(minutes=amount)
        if unit == 'h': return timedelta(hours=amount)
        if unit == 'd': return timedelta(days=amount)
        if unit == 'w': return timedelta(weeks=amount)
        return None

    # ==========================================
    # 🚫 COMMAND: BAN BANISHMENT
    # ==========================================
    @commands.hybrid_command(
        name="ban",
        description="🚫 Banish a disruptive member from the network sector (Supports Temp & Permanent)."
    )
    @app_commands.describe(
        member="The target user identity to banish from the guild matrix.",
        duration="Banishment time duration (e.g., 1m, 2h, 7d, 1w). Leave blank for permanent.",
        delete_messages="Purge message logs history generated by this entity (Default: None).",
        reason="The formal data validation log reason for this absolute banishment."
    )
    @app_commands.choices(delete_messages=[
        app_commands.Choice(name="Don't Delete Any Messages", value=0),
        app_commands.Choice(name="Previous 24 Hours (1 Day)", value=86400),
        app_commands.Choice(name="Previous 7 Days (1 Week)", value=604800)
    ])
    @commands.guild_only()
    @commands.has_permissions(ban_members=True)
    @commands.bot_has_permissions(ban_members=True)
    async def ban_command(
        self, 
        ctx: commands.Context, 
        member: discord.Member, 
        duration: Optional[str] = None,
        delete_messages: Optional[int] = 0,
        *, 
        reason: Optional[str] = "No analytical reason specified by authority."
    ):
        """Executes a banishment protocol against a target node, closing access keys."""
        
        # ถอด ctx.defer() ออกจากจุดนี้ เพราะย้ายไปตอบกลับสดผ่านการเช็ค Security หรือใช้ตามสถานการณ์

        # 🛑 SECURITY LAYER 1
        if member.id == ctx.author.id:
            embed_err = discord.Embed(description="<:No:1517480787744784475> **Termination Aborted:** You cannot banish your own node.", color=0xE74C3C)
            return await ctx.send(embed=embed_err, ephemeral=True)

        # 🛑 SECURITY LAYER 2
        if member.id == ctx.guild.owner_id:
            embed_err = discord.Embed(description="<:No:1517480787744784475> **Termination Aborted:** Target node holds the ultimate ownership key.", color=0xE74C3C)
            return await ctx.send(embed=embed_err, ephemeral=True)

        # 🛑 SECURITY LAYER 3
        if ctx.author.id != ctx.guild.owner_id and ctx.author.top_role <= member.top_role:
            embed_err = discord.Embed(description="<:No:1517480787744784475> **Access Denied:** Your authorization clearance rank is too low.", color=0xE74C3C)
            return await ctx.send(embed=embed_err, ephemeral=True)

        # 🛑 SECURITY LAYER 4
        if member.top_role >= ctx.guild.me.top_role:
            embed_err = discord.Embed(description="<:No:1517480787744784475> **Execution Failure:** Core Mainframe lacks hierarchical authority.", color=0xE74C3C)
            return await ctx.send(embed=embed_err, ephemeral=True)

        # ⏳ TIME CALCULATOR
        unban_time = None
        duration_label = "PERMANENT MATRIX BLOCK"
        
        if duration:
            parsed_time = self.parse_duration(duration)
            if not parsed_time:
                embed_err = discord.Embed(
                    description="<:No:1517480787744784475> **Format Invalid:** Duration syntax error. Use formats like `1m`, `2h`, `5d`, or `1w`.",
                    color=0xE74C3C
                )
                return await ctx.send(embed=embed_err, ephemeral=True)
            unban_time = datetime.now(timezone.utc) + parsed_time
            duration_label = f"TEMPORARY ({duration.upper()})"

        # บอทเริ่มทำงานหนัก สั่ง Defer เพื่อป้องกันการ Timeout 
        await ctx.defer()

        # 📩 DM NOTIFICATION
        try:
            dm_embed = discord.Embed(
                title=f"🚨 Banishment Matrix Activated: {ctx.guild.name}",
                description=f"Your profile signature has been restricted. Duration: `{duration_label}`",
                color=0xE74C3C,
                timestamp=datetime.now(timezone.utc)
            )
            dm_embed.add_field(name="📄 Banishment Enforcement Reason", value=f"> {reason}", inline=False)
            if unban_time:
                dm_embed.add_field(name="⏳ Estimated Restoration Time", value=f"<t:{int(unban_time.timestamp())}:F>", inline=False)
            dm_embed.set_footer(text="Automated Justice Protocol")
            await member.send(embed=dm_embed)
        except discord.HTTPException:
            pass

        # 🚫 EXECUTION LAYER
        try:
            await ctx.guild.ban(
                member, 
                delete_message_seconds=delete_messages, 
                reason=f"[{duration_label}] Enforced by {ctx.author} | Reason: {reason}"
            )
            
            # 💾 DATABASE HANDLING (บันทึกเฉพาะเคสแบนชั่วคราว)
            if unban_time:
                ban_data = {
                    "_id": f"{ctx.guild.id}-{member.id}", # รวม ID ป้องกันข้อมูลซ้ำซ้อน
                    "guild_id": ctx.guild.id,
                    "user_id": member.id,
                    "unban_time": unban_time # TTL Index จะคอยลบฟิลด์นี้เมื่อเวลาปัจจุบันเดินมาถึง
                }
                # บันทึกหรือเขียนทับถ้ามีเคสเดิมค้างอยู่
                await self.ban_collection.replace_one({"_id": ban_data["_id"]}, ban_data, upsert=True)

            # 📊 SUCCESS EMBED RESPONSE
            success_embed = discord.Embed(
                title="🚫 Banishment Protocol Registered",
                color=self.embed_color,
                timestamp=datetime.now(timezone.utc)
            )
            success_embed.add_field(name="👤 Banishment Node", value=f"{member.mention} (`{member.id}`)", inline=True)
            success_embed.add_field(name="👑 Authorized By", value=f"{ctx.author.mention}", inline=True)
            success_embed.add_field(name="⏳ Timeline Status", value=f"`{duration_label}`", inline=True)
            
            if unban_time:
                success_embed.add_field(name="📅 Automatic Release", value=f"<t:{int(unban_time.timestamp())}:R>", inline=False)
                
            purge_status = "No data purged." if delete_messages == 0 else f"Purged logs from past `{delete_messages // 3600}` hours."
            success_embed.add_field(name="🧹 Log Cache Purge", value=f"`{purge_status}`", inline=False)
            success_embed.add_field(name="📝 Reason Log Matrix", value=f"```\n{reason}\n```", inline=False)
            
            success_embed.set_thumbnail(url=member.display_avatar.url)
            success_embed.set_footer(text="Sector Perimeter Lockout Secured")

            # ใช้ ctx.interaction.followup.send แทน ctx.send เพราะเราใช้ ctx.defer() ไปก่อนหน้านี้
            await ctx.interaction.followup.send(embed=success_embed)

        except discord.HTTPException as e:
            embed_err = discord.Embed(
                description=f"<:No:1517480787744784475> **API Gateway Error:** Failed to execute ban sequence:\n`{str(e)}`",
                color=0xE74C3C
            )
            await ctx.interaction.followup.send(embed=embed_err, ephemeral=True)

    # ==========================================
    # 🕒 BACKGROUND AUTOMATED UNBAN TASK
    # ==========================================
    @tasks.loop(seconds=30.0)
    async def unban_monitor_loop(self):
        """ลูปเบื้องหลังเพื่อคอยตรวจสอบและปลดแบนยูสเซอร์ที่ถึงเวลาแล้วออกจากเซิร์ฟเวอร์ดิสคอร์ด"""
        await self.bot.wait_until_ready()
        now = datetime.now(timezone.utc)
        
        # ดึงรายชื่อที่หมดเวลาแล้วออกมาทำงาน
        cursor = self.ban_collection.find({"unban_time": {"$lte": now}})
        expired_bans = await cursor.to_list(length=100)
        
        for ban in expired_bans:
            guild = self.bot.get_guild(ban["guild_id"])
            if guild:
                try:
                    user = await self.bot.fetch_user(ban["user_id"])
                    await guild.unban(user, reason="System Restorated: Temp-ban timeline expired.")
                except discord.NotFound:
                    pass # หาประวัติแบนไม่เจอ (อาจโดนปลดแบนมือไปก่อนแล้ว)
                except discord.HTTPException:
                    continue # เกิดปัญหา API ค่อยลองใหม่ลูปหน้า
            
            # ลบข้อมูลออกจาก MongoDB ทันทีหลังจากสั่ง Unban เรียบร้อย (รวมถึงเคสที่ไม่มีเซิร์ฟเวอร์อยู่แล้ว)
            await self.ban_collection.delete_one({"_id": ban["_id"]})

    @ban_command.error
    async def ban_command_error(self, ctx: commands.Context, error: commands.CommandError):
        embed = discord.Embed(title="🚨 Clearance Verification Failure", color=0xE74C3C)
        if isinstance(error, commands.MissingPermissions):
            embed.description = "<:No:1517480787744784475> **Access Denied:** You lack `Ban Members` permission."
        elif isinstance(error, commands.BotMissingPermissions):
            embed.description = "<:No:1517480787744784475> **System Fault:** The bot lacks `Ban Members` permission."
        else:
            embed.description = f"An unexpected error occurred:\n`{str(error)}`"
        
        # ป้องกันปัญหากรณีเกิด error หลังจากสั่ง defer ไปแล้ว
        if ctx.interaction.response.is_done():
            await ctx.interaction.followup.send(embed=embed, ephemeral=True)
        else:
            await ctx.send(embed=embed, ephemeral=True)

async def setup(bot: commands.Bot):
    cog = Ban(bot)
    await bot.add_cog(cog)
    await cog.cog_load() # สั่งลงทะเบียน TTL Index ตอนโหลด Cog
